#target_file_name: count_hist_total_SoftDropGroom_rG_jetr0.4_ptj{}-{}_rapj0.0-2.1_pt0.0-5020.0_rap0.0-3.0_beta0.00_zCut0.20.txt
target_file_name: count_hist_total_SoftDropGroom_rG_jetr0.4_ptj{}-{}_rapj0.0-0.5_pt0.0-100.0_rap0.0-1.0_{}.txt

beta_zcut_list: ['beta0.00_zCut0.20']
main_results_tail: 'MainResults'
pt_rg_2d_filename: 'atlas_{}_pt_rg.txt'
rg_1d_filename: 'atlas_{}_rg_pt{}-{}.txt'
pt_1d_filename: 'atlas_{}_pt_rg0p{}-0p{}.txt'


rg_bin_finest: [-1000., 0., 0.003, 0.0042, 0.0063, 0.0096, 0.0145, 0.0220, 0.0332, 0.0503, 0.0761, 0.1153, 0.1745, 0.2642, 0.4]
rg_bin_combine: [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[10,11],[11,12],[12,13],[13,14],[1,7],[7,11],[11,13],[0,14]]


pt_bin_finest: [10.,30.,50.]
pt_bin_combine: [[0,1],[1,2],[0,2]]